# Generated by Django 3.1.5 on 2021-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matriculation_number',
            field=models.CharField(max_length=10),
        ),
    ]
