# Generated by Django 3.1.5 on 2021-01-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
