# Generated by Django 3.1.5 on 2021-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0002_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Covid 19'), ('2', 'Hall XI')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
