# Generated by Django 3.1.5 on 2021-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0003_user_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
