# Generated by Django 3.1.5 on 2021-01-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0004_auto_20210111_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rarity', models.CharField(choices=[('1', 'Common'), ('2', 'Rare'), ('3', 'Super Rare'), ('4', 'Legendary')], max_length=1)),
                ('type', models.CharField(choices=[('1', 'Attack'), ('2', 'Heal'), ('3', 'Hall XI Merchandise')], max_length=1)),
                ('value', models.IntegerField(blank=True)),
            ],
        ),
    ]
