# Generated by Django 3.1.5 on 2021-01-09 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0004_auto_20210109_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)]),
        ),
    ]
