# Generated by Django 3.1.5 on 2021-01-09 07:22

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0005_user_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
