# Generated by Django 3.1.5 on 2021-01-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
