# Generated by Django 3.1.5 on 2021-01-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0008_auto_20210110_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='user',
            name='room_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='hp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.CharField(default=1092, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='block',
            field=models.CharField(choices=[('53', '53'), ('54', '54'), ('55', '55'), ('56', '56')], default=55, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
