# Generated by Django 3.1.5 on 2021-01-10 08:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0009_auto_20210110_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hp',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
