# Generated by Django 3.1.5 on 2021-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0010_auto_20210117_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedquestion',
            name='answered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
