# Generated by Django 3.1.5 on 2021-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0013_auto_20210119_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_checked',
            field=models.BooleanField(default=False),
        ),
    ]
