# Generated by Django 3.1.5 on 2021-01-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0014_profile_has_checked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedlocation',
            unique_together={('user', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='assignedquestion',
            unique_together={('user', 'question')},
        ),
    ]
