# Generated by Django 3.1.5 on 2021-01-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0015_auto_20210119_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_assigned_question_question', to='qrhunt.question'),
        ),
        migrations.AlterField(
            model_name='assignedquestion',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
