# Generated by Django 3.1.5 on 2021-01-20 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0017_auto_20210120_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hp',
            new_name='max_hp',
        ),
        migrations.RemoveField(
            model_name='block',
            name='exploration',
        ),
        migrations.AddField(
            model_name='block',
            name='max_exploration',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
