# Generated by Django 3.1.5 on 2021-01-20 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0018_auto_20210120_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='max_exploration',
        ),
        migrations.AddField(
            model_name='block',
            name='max_exploration_points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
