# Generated by Django 3.1.5 on 2021-01-21 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0023_hplog_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hplog',
            old_name='block',
            new_name='target_block',
        ),
    ]
