# Generated by Django 3.1.5 on 2021-01-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0025_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(height_field=660, null=True, upload_to='locations/', width_field=870),
        ),
    ]
