# Generated by Django 3.1.5 on 2021-01-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0027_auto_20210121_2020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedquestion',
            unique_together=set(),
        ),
    ]
