# Generated by Django 3.1.5 on 2021-01-26 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0028_auto_20210127_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedquestion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
