# Generated by Django 3.1.5 on 2021-01-30 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0029_assignedquestion_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedLootBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('time_opened', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_assigned_loot_box_item', to='qrhunt.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_assigned_loot_box_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Assigned Loot Boxes',
            },
        ),
    ]
