# Generated by Django 3.1.5 on 2021-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0031_auto_20210130_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigneditem',
            old_name='used_time',
            new_name='time_used',
        ),
        migrations.AddField(
            model_name='assigneditem',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
