# Generated by Django 3.1.5 on 2021-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0032_auto_20210130_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigneditem',
            name='has_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignedlootbox',
            name='has_opened',
            field=models.BooleanField(default=False),
        ),
    ]
