# Generated by Django 3.1.5 on 2021-01-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0033_auto_20210130_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
