# Generated by Django 3.1.5 on 2021-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0034_assigneditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigneditem',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
