# Generated by Django 3.1.5 on 2021-03-01 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qrhunt.utils


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0035_auto_20210130_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedquestion',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PhotoUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_photo_upvote_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', qrhunt.utils.ContentTypeRestrictedFileField(upload_to='submissions/')),
                ('has_reviewed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_photo_submission_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
