# Generated by Django 3.1.5 on 2021-03-01 11:42

from django.db import migrations, models
import qrhunt.utils


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0036_auto_20210301_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosubmission',
            name='title',
            field=models.CharField(default='Test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photosubmission',
            name='photo',
            field=qrhunt.utils.ContentTypeRestrictedFileField(upload_to=qrhunt.utils.update_filename),
        ),
    ]
