# Generated by Django 3.1.5 on 2021-03-01 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0037_auto_20210301_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoupvote',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_photo_upvote_photo_submission', to='qrhunt.photosubmission'),
            preserve_default=False,
        ),
    ]
