# Generated by Django 3.1.5 on 2021-03-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrhunt', '0039_photocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocomment',
            name='submission',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='fk_photo_comment_photo_submission', to='qrhunt.photosubmission'),
            preserve_default=False,
        ),
    ]
